import { Inter } from 'next/font/google'
// import Navbar from './_components'
import './global.css'
import Header from '@/Header/Component'

const inter = Inter({ subsets: ['latin-ext'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
